/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admintabs/AdminDashboard`; params?: Router.UnknownInputParams; } | { pathname: `/auth/AdminLogin`; params?: Router.UnknownInputParams; } | { pathname: `/auth/otpVerify`; params?: Router.UnknownInputParams; } | { pathname: `/auth/customer/customerLogin`; params?: Router.UnknownInputParams; } | { pathname: `/auth/customer/customerSignUp`; params?: Router.UnknownInputParams; } | { pathname: `/auth/serviceProvider/serviceProviderLogin`; params?: Router.UnknownInputParams; } | { pathname: `/customerTabs/BookingHistory`; params?: Router.UnknownInputParams; } | { pathname: `/customerTabs/EditProfile`; params?: Router.UnknownInputParams; } | { pathname: `/customerTabs/home`; params?: Router.UnknownInputParams; } | { pathname: `/customerTabs/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/customerTabs/bookSteps/bookStep1`; params?: Router.UnknownInputParams; } | { pathname: `/customerTabs/bookSteps/bookStep2`; params?: Router.UnknownInputParams; } | { pathname: `/customerTabs/bookSteps/bookStep3`; params?: Router.UnknownInputParams; } | { pathname: `/customerTabs/bookSteps/bookStep4`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admintabs/AdminDashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/AdminLogin`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/otpVerify`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/customer/customerLogin`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/customer/customerSignUp`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/serviceProvider/serviceProviderLogin`; params?: Router.UnknownOutputParams; } | { pathname: `/customerTabs/BookingHistory`; params?: Router.UnknownOutputParams; } | { pathname: `/customerTabs/EditProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/customerTabs/home`; params?: Router.UnknownOutputParams; } | { pathname: `/customerTabs/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/customerTabs/bookSteps/bookStep1`; params?: Router.UnknownOutputParams; } | { pathname: `/customerTabs/bookSteps/bookStep2`; params?: Router.UnknownOutputParams; } | { pathname: `/customerTabs/bookSteps/bookStep3`; params?: Router.UnknownOutputParams; } | { pathname: `/customerTabs/bookSteps/bookStep4`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admintabs/AdminDashboard${`?${string}` | `#${string}` | ''}` | `/auth/AdminLogin${`?${string}` | `#${string}` | ''}` | `/auth/otpVerify${`?${string}` | `#${string}` | ''}` | `/auth/customer/customerLogin${`?${string}` | `#${string}` | ''}` | `/auth/customer/customerSignUp${`?${string}` | `#${string}` | ''}` | `/auth/serviceProvider/serviceProviderLogin${`?${string}` | `#${string}` | ''}` | `/customerTabs/BookingHistory${`?${string}` | `#${string}` | ''}` | `/customerTabs/EditProfile${`?${string}` | `#${string}` | ''}` | `/customerTabs/home${`?${string}` | `#${string}` | ''}` | `/customerTabs/Profile${`?${string}` | `#${string}` | ''}` | `/customerTabs/bookSteps/bookStep1${`?${string}` | `#${string}` | ''}` | `/customerTabs/bookSteps/bookStep2${`?${string}` | `#${string}` | ''}` | `/customerTabs/bookSteps/bookStep3${`?${string}` | `#${string}` | ''}` | `/customerTabs/bookSteps/bookStep4${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admintabs/AdminDashboard`; params?: Router.UnknownInputParams; } | { pathname: `/auth/AdminLogin`; params?: Router.UnknownInputParams; } | { pathname: `/auth/otpVerify`; params?: Router.UnknownInputParams; } | { pathname: `/auth/customer/customerLogin`; params?: Router.UnknownInputParams; } | { pathname: `/auth/customer/customerSignUp`; params?: Router.UnknownInputParams; } | { pathname: `/auth/serviceProvider/serviceProviderLogin`; params?: Router.UnknownInputParams; } | { pathname: `/customerTabs/BookingHistory`; params?: Router.UnknownInputParams; } | { pathname: `/customerTabs/EditProfile`; params?: Router.UnknownInputParams; } | { pathname: `/customerTabs/home`; params?: Router.UnknownInputParams; } | { pathname: `/customerTabs/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/customerTabs/bookSteps/bookStep1`; params?: Router.UnknownInputParams; } | { pathname: `/customerTabs/bookSteps/bookStep2`; params?: Router.UnknownInputParams; } | { pathname: `/customerTabs/bookSteps/bookStep3`; params?: Router.UnknownInputParams; } | { pathname: `/customerTabs/bookSteps/bookStep4`; params?: Router.UnknownInputParams; };
    }
  }
}
