"""Add booking cancellation fields

Revision ID: 5e008abcb0a8
Revises: 7dd0de8dc354
Create Date: 2025-09-13 16:18:34.157796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e008abcb0a8'
down_revision = '7dd0de8dc354'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('canceled_by', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('bookings', 'canceled_at')
    op.drop_column('bookings', 'canceled_by')
    op.drop_column('bookings', 'cancellation_reason')
    # ### end Alembic commands ###