"""add hashed_password to users

Revision ID: 7dd0de8dc354
Revises: 
Create Date: 2025-09-06 20:46:45.714527

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7dd0de8dc354'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # Step 1: Add as nullable
    op.add_column('users', sa.Column('hashed_password', sa.String(255), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))

    # Step 2: Fill with a placeholder value for existing users
    op.execute("UPDATE users SET hashed_password = 'changeme' WHERE hashed_password IS NULL")

    # Step 3: Alter to NOT NULL
    op.alter_column('users', 'hashed_password', nullable=False)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###